seed: 0                           # Seed of all experiments
optimize:
  optimizer: Adam                 # Name of the optimizer
  lr: 0.001                       # Learning rate
  scheduler: ReduceLROnPlateau    # Name of the scheduler None/null for no scheduler
  scheduler_settings:             # Scheduler settings
    mode: min
    factor: 0.1
    patience: 3
    threshold: 2
    verbose: true
train:                            # Training settings
  epochs: 1                       # Number of epochs
  batch_size: 16                  # Batch size
  early_stopping: false           # Use Early stopping    
  early_stopping_settings:        # Early stopping settings
      monitor: val-MAE
      min_delta: 0.1
      patience: 5
      mode:  min
      verbose: true
model:
  name: peakdetection1d            # Model to use (resnet2d, resnet1d, transformer1d, transformer2d)
  data_dim: 1d                    # Dimensions of input (1d, 2d, 3d)
  input_representation: traces    # Input Representation (cwt, traces, ibis)
  target: HR                      # Prediction target (AUP, RT, PWA, HR)
dataset:
  name: vicar                     # Dataset to use (vipl, vicar)
  root: ./TrainingData            # Path to the preprocessed data
  num_workers: 1                  # Number of workers for the dataloader
  fold_number: 0                  # Number of the fold to use (defined in src/constatst.py)
  use_gt: false                   # Use resampled ground truth data for training
  use_yuv: false                  # (legacy) Use YUV data for training
comet:
  api_key: # Your comet api key
  workspace: # Your comet workspace
  project_name: # Your comet project name

