seed: 0
optimize:
  optimizer: Adam
  lr: 0.001
  scheduler: ReduceLROnPlateau
  scheduler_settings:
    mode: min
    factor: 0.1
    patience: 3
train:
  epochs: 1
  batch_size: 1
  early_stopping: true
  early_stopping_settings:
      monitor: val-MAE
      min_delta: 0.01
      patience: 5
      mode:  min
model:
model:
  name: resnet2d #transformer1d #resnet2d #resnet1d #resnet2d #transformer1d #
  data_dim: 3d #1d #2d #2d #1d #3d #1d
  input_representation: ibis #traces #cwt #cwt #traces #ibis #traces #cwt, ibis
  target: HR #AUP # RT,PWA,HR
dataset:
  name: vipl #vicar #vipl  
  root: ./TrainingData #./OutputFolder/data # ./TrainingData
  num_workers: 1
  fold_number: 0
  use_gt: false 
  use_yuv: false
comet:
  api_key: 
  workspace: 
  project_name: 
# wandb:
#   log: true
#   dir: ./
#   experiment_name: ''
#   entity: ''
#   project: ''