vicar:
  dataset_path:
  video_suffix: .avi
  traces_path: # Path to your dataset traces
  traces_fps: 30                          # Fps of the traces
  gt_path: # Path to the ground truth data
  gt_fps: 500                             # Fps of the ground truth data
  gt_type: h5py                           # Type of the ground truth data (h5py, numpy)  
  test_ids: [6, 8]                        # Default Participant ids to use for testing
  val_ids: [1, 10]                        # Default Participant ids to use for validation
vipl:
  dataset_path: # Path to your dataset
  video_suffix: .avi
  traces_path: # Path to your dataset traces
  traces_fps: 25                                                             # Fps of the traces                         
  gt_path: # Path to the ground truth data
  gt_fps: 60                                                                 # Fps of the ground truth data
  gt_type: numpy                                                             # Type of the ground truth data (h5py, numpy)  
  test_ids: [19, 62, 86, 67, 37, 77, 40, 7, 36, 100, 83, 89, 6, 45, 32, 22]  # Default Participant ids to use for testing
  val_ids: [33, 97, 98, 69, 71, 103, 9, 59, 43, 12, 104, 50, 88, 90, 27, 61] # Default Participant ids to use for validation
